const WorkflowState = {
  UPLOADED: "UPLOADED",
  PARSING: "PARSING",
  STRUCTURE_DETECTED: "STRUCTURE_DETECTED",
  EXTRACTING: "EXTRACTING",
  AGGREGATING: "AGGREGATING",
  VALIDATING: "VALIDATING",
  LOW_CONFIDENCE: "LOW_CONFIDENCE",
  ANALYZING: "ANALYZING",
  GENERATING_REPORT: "GENERATING_REPORT",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED"
};

module.exports = { WorkflowState };
