# Canonical service-level error code constants.
MISSING_DOCUMENT_CHUNKS_IN_REDIS = "missing_document_chunks_in_redis"
NO_RELEVANT_BALANCE_SHEET_CHUNKS = "no_relevant_balance_sheet_chunks"
CHUNK_EXTRACTION_ORCHESTRATION_ERROR = "chunk_extraction_orchestration_error"
ALL_CHUNK_EXTRACTIONS_FAILED = "all_chunk_extractions_failed"
GEMINI_OR_TRANSFORM_ERROR = "gemini_or_transform_error"
EXTRACTION_ERROR = "extraction_error"
TRANSFORMATION_ERROR = "transformation_error"
PERSIST_RESULT_FAILED = "persist_result_failed"
NO_RELEVANT_CHUNKS = "no_relevant_chunks"
