/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidationRouteImport } from './routes/validation'
import { Route as ReprocessingRouteImport } from './routes/reprocessing'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProcessingRouteImport } from './routes/processing'
import { Route as MappingRouteImport } from './routes/mapping'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardYearAnalysisRouteImport } from './routes/dashboard.year-analysis'
import { Route as DashboardRiskRouteImport } from './routes/dashboard.risk'
import { Route as DashboardPatternsRouteImport } from './routes/dashboard.patterns'
import { Route as DashboardCalculationsRouteImport } from './routes/dashboard.calculations'

const ValidationRoute = ValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => rootRouteImport,
} as any)
const ReprocessingRoute = ReprocessingRouteImport.update({
  id: '/reprocessing',
  path: '/reprocessing',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessingRoute = ProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const MappingRoute = MappingRouteImport.update({
  id: '/mapping',
  path: '/mapping',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardYearAnalysisRoute = DashboardYearAnalysisRouteImport.update({
  id: '/year-analysis',
  path: '/year-analysis',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRiskRoute = DashboardRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPatternsRoute = DashboardPatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalculationsRoute = DashboardCalculationsRouteImport.update({
  id: '/calculations',
  path: '/calculations',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/mapping': typeof MappingRoute
  '/processing': typeof ProcessingRoute
  '/register': typeof RegisterRoute
  '/reprocessing': typeof ReprocessingRoute
  '/validation': typeof ValidationRoute
  '/dashboard/calculations': typeof DashboardCalculationsRoute
  '/dashboard/patterns': typeof DashboardPatternsRoute
  '/dashboard/risk': typeof DashboardRiskRoute
  '/dashboard/year-analysis': typeof DashboardYearAnalysisRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/mapping': typeof MappingRoute
  '/processing': typeof ProcessingRoute
  '/register': typeof RegisterRoute
  '/reprocessing': typeof ReprocessingRoute
  '/validation': typeof ValidationRoute
  '/dashboard/calculations': typeof DashboardCalculationsRoute
  '/dashboard/patterns': typeof DashboardPatternsRoute
  '/dashboard/risk': typeof DashboardRiskRoute
  '/dashboard/year-analysis': typeof DashboardYearAnalysisRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/mapping': typeof MappingRoute
  '/processing': typeof ProcessingRoute
  '/register': typeof RegisterRoute
  '/reprocessing': typeof ReprocessingRoute
  '/validation': typeof ValidationRoute
  '/dashboard/calculations': typeof DashboardCalculationsRoute
  '/dashboard/patterns': typeof DashboardPatternsRoute
  '/dashboard/risk': typeof DashboardRiskRoute
  '/dashboard/year-analysis': typeof DashboardYearAnalysisRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/dashboard'
    | '/login'
    | '/mapping'
    | '/processing'
    | '/register'
    | '/reprocessing'
    | '/validation'
    | '/dashboard/calculations'
    | '/dashboard/patterns'
    | '/dashboard/risk'
    | '/dashboard/year-analysis'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/login'
    | '/mapping'
    | '/processing'
    | '/register'
    | '/reprocessing'
    | '/validation'
    | '/dashboard/calculations'
    | '/dashboard/patterns'
    | '/dashboard/risk'
    | '/dashboard/year-analysis'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/dashboard'
    | '/login'
    | '/mapping'
    | '/processing'
    | '/register'
    | '/reprocessing'
    | '/validation'
    | '/dashboard/calculations'
    | '/dashboard/patterns'
    | '/dashboard/risk'
    | '/dashboard/year-analysis'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  MappingRoute: typeof MappingRoute
  ProcessingRoute: typeof ProcessingRoute
  RegisterRoute: typeof RegisterRoute
  ReprocessingRoute: typeof ReprocessingRoute
  ValidationRoute: typeof ValidationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validation': {
      id: '/validation'
      path: '/validation'
      fullPath: '/validation'
      preLoaderRoute: typeof ValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reprocessing': {
      id: '/reprocessing'
      path: '/reprocessing'
      fullPath: '/reprocessing'
      preLoaderRoute: typeof ReprocessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processing': {
      id: '/processing'
      path: '/processing'
      fullPath: '/processing'
      preLoaderRoute: typeof ProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapping': {
      id: '/mapping'
      path: '/mapping'
      fullPath: '/mapping'
      preLoaderRoute: typeof MappingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/year-analysis': {
      id: '/dashboard/year-analysis'
      path: '/year-analysis'
      fullPath: '/dashboard/year-analysis'
      preLoaderRoute: typeof DashboardYearAnalysisRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/risk': {
      id: '/dashboard/risk'
      path: '/risk'
      fullPath: '/dashboard/risk'
      preLoaderRoute: typeof DashboardRiskRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/patterns': {
      id: '/dashboard/patterns'
      path: '/patterns'
      fullPath: '/dashboard/patterns'
      preLoaderRoute: typeof DashboardPatternsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calculations': {
      id: '/dashboard/calculations'
      path: '/calculations'
      fullPath: '/dashboard/calculations'
      preLoaderRoute: typeof DashboardCalculationsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardCalculationsRoute: typeof DashboardCalculationsRoute
  DashboardPatternsRoute: typeof DashboardPatternsRoute
  DashboardRiskRoute: typeof DashboardRiskRoute
  DashboardYearAnalysisRoute: typeof DashboardYearAnalysisRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCalculationsRoute: DashboardCalculationsRoute,
  DashboardPatternsRoute: DashboardPatternsRoute,
  DashboardRiskRoute: DashboardRiskRoute,
  DashboardYearAnalysisRoute: DashboardYearAnalysisRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  MappingRoute: MappingRoute,
  ProcessingRoute: ProcessingRoute,
  RegisterRoute: RegisterRoute,
  ReprocessingRoute: ReprocessingRoute,
  ValidationRoute: ValidationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
